export interface TFreeBot {
    id: string;
    name: string;
    description: string;
    category: 'Automatic' | 'Hybrid' | 'Normal' | 'Popular';
    xmlPath: string;
    isPremium: boolean;
    isNew?: boolean;
    icon?: string;
    color?: string;
}

export const FREE_BOTS_DATA: TFreeBot[] = [
    {
        id: 'premium-speedbot',
        name: 'Profithub Speedbot',
        description: 'Fast execution bot for volatility indices with smart martingale.',
        category: 'Automatic',
        xmlPath: 'Normal Bots/Profithub Speedbot.xml',
        isPremium: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-over-under',
        name: 'OVER UNDER AUTO SWITCHER',
        description: 'Switches between over and under based on market logic.',
        category: 'Automatic',
        xmlPath: 'Automatic/OVER UNDER AUTO SWITCHER.xml',
        isPremium: false,
        color: '#f59e0b',
    },
    {
        id: 'hybrid-trend-reversal',
        name: 'Trend Reversal Hybrid',
        description: 'Combined trend following and mean reversion strategy.',
        category: 'Hybrid',
        xmlPath: 'Hybrid/Trend Reversal.xml',
        isPremium: false,
        color: '#14b8a6',
    },
    {
        id: 'normal-simple-martingale',
        name: 'Simple Martingale',
        description: 'Classic martingale strategy for consistent small gains.',
        category: 'Normal',
        xmlPath: 'Normal Bots/Simple Martingale.xml',
        isPremium: false,
        color: '#3b82f6',
    },
    {
        id: 'popular-digit-reaper',
        name: 'Digit Reaper',
        description: 'Optimized for digit contracts with high win rate.',
        category: 'Popular',
        xmlPath: 'Popular/Digit Reaper.xml',
        isPremium: false,
        color: '#a855f7',
    },
    {
        id: 'normal-speedbot-updated',
        name: 'SPEED BOT updated',
        description: 'Updated version of the popular speed bot strategy.',
        category: 'Normal',
        xmlPath: 'Normal Bots/SPEED BOT updated.xml',
        isPremium: false,
        color: '#3b82f6',
    },
    // New Advanced Consolidates
    {
        id: 'auto-even-odd-new',
        name: 'Official Even/Odd Bot',
        description: 'Advanced Even/Odd strategy with 55% power threshold and trend analysis.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Even_Odd_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-over-under-new',
        name: 'Official Over/Under Bot',
        description: 'Predicts Over/Under based on market bias and increasing digit power.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Over_Under_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-differs-new',
        name: 'Official Differs Bot',
        description: 'Targets digits with decreasing power, avoiding most/least appearing digits.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Differs_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-matches-new',
        name: 'Official Matches Bot',
        description: 'High-frequency trading engine that matches digits using power surge analysis.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Matches_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    // The 8 Specialized Bots
    {
        id: 'auto-over-0',
        name: 'Over 0 Bot',
        description: 'Specialized Over 0 strategy with auto market switching.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Over_0_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-over-1',
        name: 'Over 1 Bot',
        description: 'Specialized Over 1 strategy with auto market switching.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Over_1_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-over-2',
        name: 'Over 2 Bot',
        description: 'Specialized Over 2 strategy with auto market switching.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Over_2_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-over-3',
        name: 'Over 3 Bot',
        description: 'Specialized Over 3 strategy with auto market switching.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Over_3_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-under-9',
        name: 'Under 9 Bot',
        description: 'Specialized Under 9 strategy with auto market switching.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Under_9_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-under-8',
        name: 'Under 8 Bot',
        description: 'Specialized Under 8 strategy with auto market switching.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Under_8_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-under-7',
        name: 'Under 7 Bot',
        description: 'Specialized Under 7 strategy with auto market switching.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Under_7_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-under-6',
        name: 'Under 6 Bot',
        description: 'Specialized Under 6 strategy with auto market switching.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Under_6_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
];
