export interface TFreeBot {
    id: string;
    name: string;
    description: string;
    category: 'Automatic' | 'Hybrid';
    xmlPath: string;
    isPremium: boolean;
    isNew?: boolean;
    icon?: string;
    color?: string;
}

export const FREE_BOTS_DATA: TFreeBot[] = [
    // HYBRID BOTS (Elite Strategies)
    {
        id: 'guardian-under',
        name: 'The Guardian Under',
        description: 'Elite Sequential Under 9 -> Under 8 strategy with Under 4 recovery and market intelligence.',
        category: 'Hybrid',
        xmlPath: 'Official Bots/Guardian_Under.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'titan-over',
        name: 'The Titan Over',
        description: 'Elite Sequential Over 0 -> Over 1 strategy with Over 5 recovery and market intelligence.',
        category: 'Hybrid',
        xmlPath: 'Official Bots/Titan_Over.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'unstoppable-switcher',
        name: 'Unstoppable Even/Odd Switcher',
        description: 'Automatically switches between Even and Odd with massive power analysis and strict pattern entry.',
        category: 'Hybrid',
        xmlPath: 'Official Bots/Even_Odd_Auto_Switcher.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'compounding-bot',
        name: 'Compounding Bot',
        description: 'Reinvests winnings into the next stake for exponential growth.',
        category: 'Hybrid',
        xmlPath: 'Official Bots/Compounding_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'over-under-compounding',
        name: 'The Titan Compounding',
        description: 'Elite Over 1,2 and Under 7,8 strategy with auto-switching and power compounding.',
        category: 'Hybrid',
        xmlPath: 'Official Bots/Over_Under_Compounding.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'normal-speedbot-updated',
        name: 'SPEED BOT updated',
        description: 'Updated version of the popular speed bot strategy.',
        category: 'Hybrid',
        xmlPath: 'Normal Bots/SPEED BOT updated.xml',
        isPremium: false,
        color: '#3b82f6',
    },

    // AUTOMATIC BOTS (Standard Professional)
    {
        id: 'auto-even-odd-new',
        name: 'Official Even/Odd Bot',
        description: 'Advanced Even/Odd strategy with 100-tick analysis and pattern entry.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Even_Odd_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-over-under-new',
        name: 'Official Over/Under Bot',
        description: 'Predicts Over/Under based on market bias and increasing digit power.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Over_Under_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-differs-new',
        name: 'Official Differs Bot',
        description: 'Targets the least frequent digit in the last 50 ticks for high probability differs trading.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Differs_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-matches-new',
        name: 'Official Matches Bot',
        description: 'Predicts the most frequent digit in the last 50 ticks to catch matching digit correlations.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Matches_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'sequential-under-recovery',
        name: 'Sequential Under Recovery',
        description: 'Sequential Under 9-8-7 strategy with advanced loss protection and market switching.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Sequential_Under_Recovery.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'sequential-over-recovery',
        name: 'Sequential Over Recovery',
        description: 'Sequential Over 1-2-3 strategy with advanced loss protection and market switching.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Sequential_Over_Recovery.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'premium-speedbot',
        name: 'Profithub Speedbot',
        description: 'Fast execution bot for volatility indices with smart martingale.',
        category: 'Automatic',
        xmlPath: 'Normal Bots/Profithub Speedbot.xml',
        isPremium: true,
        color: '#ffdd00',
    },

    // SPECIALIZED BOTS
    {
        id: 'auto-over-0',
        name: 'Over 0 Bot',
        description: 'Specialized Over 0 strategy with auto market switching.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Over_0_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-over-1',
        name: 'Over 1 Bot',
        description: 'Specialized Over 1 strategy with auto market switching.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Over_1_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-under-9',
        name: 'Under 9 Bot',
        description: 'Specialized Under 9 strategy with auto market switching.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Under_9_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-under-8',
        name: 'Under 8 Bot',
        description: 'Specialized Under 8 strategy with auto market switching.',
        category: 'Automatic',
        xmlPath: 'Official Bots/Under_8_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
];
